export const types = [
    1,
    Number,
    true,
    Boolean,
    'val',
    String,
    [],
    Array,
    {},
    Object,
    (): void => {},
    Function,
    Symbol,
    Symbol(),
    null,
    undefined,
    // eslint-disable-next-line @typescript-eslint/no-extraneous-class
    class C {},
    // eslint-disable-next-line @typescript-eslint/no-extraneous-class
    new class C {},
    BigInt,
    Map,
    new Map,
    Set,
    new Set,
    WeakSet,
    new WeakSet,
    Date,
    new Date,
    FormData,
    new FormData,
    Event
];
