name: Build

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    paths:
      - 'tsconfig.json'
      - 'rollup.config.js'
      - 'src/**/*.ts'
      - 'package-lock.json'
    branches:
      - 'release/*'

jobs:
  rollup:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm ci
      - name: Rollup
        run: npm run build
